//! This module implements the AUv2 plugin info extension of the clap-wrapper project.
//! Using these extensions, we can tell the wrapper how to advertise our CLAP plugins as AUv2.

mod sys;

use clack_common::factory::{Factory, RawFactoryPointer};
use std::ffi::CStr;
use sys::*;

#[cfg(feature = "clack-host")]
mod host;

#[cfg(feature = "clack-plugin")]
mod plugin;
#[cfg(feature = "clack-plugin")]
pub use plugin::*;

/// Plugin info for the CLAP-as-AUv2 wrapper.
///
/// This could be used to override the AUv2 type/subtype codes generated by the wrapper.
#[derive(Debug, Copy, Clone)]
pub struct PluginInfoAsAUv2 {
    inner: clap_plugin_info_as_auv2,
}

impl PluginInfoAsAUv2 {
    #[cfg(feature = "clack-host")]
    pub(crate) fn empty() -> PluginInfoAsAUv2 {
        Self {
            inner: clap_plugin_info_as_auv2 {
                au_subt: [0; 5],
                au_type: [0; 5],
            },
        }
    }

    /// Creates a new [`PluginInfoAsAUv2`] with the given AUv2 type and subtype codes.
    #[inline]
    pub fn new(au_type: &str, au_subt: &str) -> Self {
        assert_eq!(
            au_type.len(),
            4,
            "au_type must be exactly 4 characters long"
        );
        assert_eq!(
            au_subt.len(),
            4,
            "au_subt must be exactly 4 characters long"
        );

        let mut inner = clap_plugin_info_as_auv2 {
            au_type: [0; 5],
            au_subt: [0; 5],
        };

        inner.au_type[..4].copy_from_slice(au_type.as_bytes());
        inner.au_subt[..4].copy_from_slice(au_subt.as_bytes());

        // Byte 4 is already zero due to array init: [0; 5]

        Self { inner }
    }

    /// Gets the AUv2 type code to use for this plugin.
    ///
    /// It is a 4-character ASCII code, stored in a 5-byte array with a null terminator.
    #[inline]
    pub const fn au_type(&self) -> &[u8; 5] {
        &self.inner.au_type
    }

    /// Gets the AUv2 subtype code to use for this plugin.
    ///
    /// It is a 4-character ASCII code, stored in a 5-byte array with a null terminator.
    #[inline]
    pub const fn au_subt(&self) -> &[u8; 5] {
        &self.inner.au_subt
    }

    /// Returns the [`PluginInfoAsAUv2`] as the raw C-FFI-compatible CLAP struct.
    #[inline]
    pub const fn as_raw(&self) -> &clap_plugin_info_as_auv2 {
        &self.inner
    }

    /// Returns the [`PluginInfoAsAUv2`] as the raw C-FFI-compatible CLAP struct.
    #[inline]
    pub const fn as_raw_mut(&mut self) -> &mut clap_plugin_info_as_auv2 {
        &mut self.inner
    }
}

/// A [`Factory`] that allows the wrapper to query extra information about the plugin for the purposes of wrapping it as a AUv2 plugin.
#[derive(Copy, Clone)]
#[allow(dead_code)]
pub struct PluginAsAuv2Factory<'a>(RawFactoryPointer<'a, clap_plugin_factory_as_auv2>);

// SAFETY: clap_plugin_factory_as_auv2 is the type matching the CLAP_PLUGIN_FACTORY_INFO_AUV2 factory ID.
unsafe impl<'a> Factory<'a> for PluginAsAuv2Factory<'a> {
    const IDENTIFIERS: &'static [&'static CStr] = &[CLAP_PLUGIN_FACTORY_INFO_AUV2];
    type Raw = clap_plugin_factory_as_auv2;

    #[inline]
    unsafe fn from_raw(raw: RawFactoryPointer<'a, Self::Raw>) -> Self {
        Self(raw)
    }
}
